import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import CartProvider from "@/contexts/CartContext";
const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
  // You can specify weights if you want to limit the bundle size,
  // or leave it variable if the font supports it.
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-manrope", // This creates a CSS variable
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${manrope.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <CartProvider>
          <Navbar />
          {children}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
